language: r

cache:
  - packages
  - ccache

sudo: required
dist: trusty
latex: false

r:
  - release

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin

env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
     - R_CODECOV=true

warnings_are_errors: false

r_check_args: "--no-build-vignettes --no-manual --as-cran"
r_build_args: "--no-build-vignettes --no-manual"

r_github_packages:
  - jimhester/covr
  
after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
